name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test on JDK ${{matrix.java-version}}
    strategy:
      matrix:
        java-version: ["openjdk@1.8", "openjdk@1.11"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: ${{ matrix.java-version }}
      - name: Run tests
        run: csbt test

  integration-test:
    name: Integration Test on JDK ${{matrix.java-version}}
    strategy:
      matrix:
        java-version: ["openjdk@1.11"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: ${{ matrix.java-version }}
      - name: Setup database
        run: docker-compose up -d
      - name: Run tests
        run: csbt it:test
